version: '3.8'
services:
  db:
    image: postgres:latest
    restart: unless-stopped
    environment:
      POSTGRES_DB: users
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
    ports:
      - 5433:5432

  main-service:
    build: ./src
    ports:
      - "5000:5000"
    environment:
      POSTGRES_DB: users
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
    depends_on:
      - db
    command: uvicorn main:app --host 0.0.0.0 --port 5000 --reload
